
version: '2'

services:
  web:
    image: startpage:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URI: db:27017
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: node --debug=0.0.0.0:5858 server.js
  
  db:
    image: mongo
